bxy:
  ip:
    mysql: ${MYSQL_IP:127.0.0.1}
  mysql:
    port: 3306
    username: root
    password: root

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://${bxy.mysql.ip}:${bxy.mysql.port}/${bxy.mysql.database}?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull
